### ISSUE TITLE
Installation documentation is out of date

### ISSUE THREAD

**Issue by drjayvee** [simplesamlphp/simplesamlphp-module-metarefresh#10]
See https://github.com/simplesamlphp/simplesamlphp/issues/1330

The [installation instruction](https://github.com/simplesamlphp/simplesamlphp-module-metarefresh/blob/master/docs/simplesamlphp-automated_metadata.md) reads

> [root@simplesamlphp] cd /var/simplesamlphp
[root@simplesamlphp simplesamlphp] touch modules/cron/enable
[root@simplesamlphp simplesamlphp] cp modules/cron/config-templates/*.php config/
[root@simplesamlphp simplesamlphp] touch modules/metarefresh/enable
[root@simplesamlphp simplesamlphp] cp modules/metarefresh/config-templates/*.php config/

But as of 1.18, `modules/metarefresh` doesn't exist.

**Comment by tvdijen** [comment]
This is an issue tracker, not a support forum. Please refer to our [mailing lists](https://simplesamlphp.org/lists)
