### ISSUE TITLE
Link to cron documentation broken

### ISSUE THREAD

**Issue by bryce13950** [simplesamlphp/simplesamlphp-module-metarefresh#13]
In the main doc that outlines how to configure this module, there are a few references to cron doc https://github.com/simplesamlphp/simplesamlphp-module-metarefresh/blob/master/docs/cron:cron, which seems to be broken.

**Comment by thijskh** [comment]
Thanks. We are in a bit of unideal situation where some docs are on github amd others on simplesamlphp.org. I’ve fixed this instance now by linking them to the cron docs on simplesamlphp.org.
