### ISSUE TITLE
metarefresh ^1.0 is not installed correctly

### ISSUE THREAD

**Issue by melanger** [simplesamlphp/simplesamlphp-module-metarefresh#15]
Hi,

I have a problem upgrading from SSP 1.19.1 to 1.19.3 because metarefresh is installed in a wrong directory. I am installing SSP as a composer package, it works for all modules and it worked for metarefresh as well.

SSP 1.19.1 requires metarefresh ^0.9, which works, it is installed into simplesamlphp/modules/metarefresh

SSP 1.19.3 requires metarefresh ^1.0, which is installed into the vendor folder under simplesamlphp-module-metarefresh. Therefore it is missing in the modules folder and cron never runs.

I guess this is caused by changes to composer.json between v0.9.6 and v1.0.1:

```patch
--- v0.9.6
+++ v1.0.1
@@ -27,15 +27,16 @@
         }
     },
     "require": {
-        "php": ">=5.6",
-        "simplesamlphp/composer-module-installer": "~1.1"
+        "php": ">=7.4 || ^8.0",
+        "simplesamlphp/composer-module-installer": "~1.1",
+        "simplesamlphp/simplesamlphp": "dev-master",
+        "simplesamlphp/assert": "~0.2.6"
     },
     "require-dev": {
-        "simplesamlphp/simplesamlphp": "^1.18",
-        "phpunit/phpunit": "~5.7"
+        "simplesamlphp/simplesamlphp-test-framework": "^1.1.0"
     },
     "support": {
-        "issues": "https://github.com/tvdijen/simplesamlphp-module-metarefresh/issues",
-        "source": "https://github.com/tvdijen/simplesamlphp-module-metarefresh"
+        "issues": "https://github.com/simplesamlphp/simplesamlphp-module-metarefresh/issues",
+        "source": "https://github.com/simplesamlphp/simplesamlphp-module-metarefresh"
     }
 }

```

I suspect `"simplesamlphp/simplesamlphp": "dev-master"`.

**Comment by tvdijen** [comment]
Yes, a problem snuck in and it was already reported and fixed on the 1.19-branch of SimpleSAMLphp..
The easiest  way for now is to downgrade metarefresh to `^0.9` until we can release 1.19.4..  It should never have been updated to 1.0...

**Comment by m0n1ker** [comment]
For anyone else struggling to get this to work a composer version alias like this will resolve the issue until 1.19.4 is released.

```json
"require": {
    "simplesamlphp/simplesamlphp": "^1.19",
    "simplesamlphp/simplesamlphp-module-metarefresh": "0.9.6 as 1.0.1"
}
```

**Comment by tvdijen** [comment]
SSP v1.19.4 was released a while back, so this problem has been solved.
