### ISSUE TITLE
composer messed up

### ISSUE THREAD

**Issue by netzkollektiv** [simplesamlphp/simplesamlphp-module-metarefresh#16]
Unfortunately, the module cannot be installed for SimpleSAML 1.19 using Composer. The only compatible version (v1.0) includes the following:

```
{
  "name": "simplesamlphp/simplesamlphp-module-metarefresh",
  "description": "The metarefresh module will download and parse metadata documents and store them locally",
  "type": "simplesamlphp-metarefresh",
```

Type must be simplesamlphp-**module** so that the module gets picked up by the composer module installer. The newer (and older) versions  correct this issue, but have version constraints which prevent the installation with SimpleSAML 1.19:

> Problem 1
>     - Root composer.json requires simplesamlphp/simplesamlphp-module-metarefresh ^1.0.2 -> satisfiable by simplesamlphp/simplesamlphp-module-metarefresh[v1.0.2].
>     - simplesamlphp/simplesamlphp-module-metarefresh v1.0.2 requires simplesamlphp/simplesamlphp ^2.0.0-beta.2 -> found simplesamlphp/simplesamlphp[v1.19.3] but it does not match the constraint. See https://getcomposer.org/dep-on-root for details and assistance.

**Comment by tvdijen** [comment]
v0.9.7 should work for you?
v1.x.x is supposed to work with SSP 2.0 beta

**Comment by tvdijen** [comment]
I''ve removed the 1.0.0 tag, since it is broken..

**Comment by tvdijen** [comment]
I now see you are using an outdated version of SimpleSAMLphp.. This issue has already been resolved in the latest stable release.
