### ISSUE TITLE
SSP 2.x

### ISSUE THREAD

**Issue by isrjo** [simplesamlphp/simplesamlphp-module-metarefresh#21]
Under the impression the current state of this project is incompatible with v2 of SimpleSamlPHP. I wrote a oneliner to restore that, but my lack of php-skills as well as the non-existing knowledge of this project makes it impossibe to decide wherer or not that is considered sufficient. It most probably breaks all backward compatibility

The commit is found here do with it as you please
https://github.com/isrjo/simplesamlphp-module-metarefresh/commit/58e7dec9ae1893380bddcb63144789bb0e049f4d

Tested against simplesamlphp 2.0.0-rc2.

**Comment by tvdijen** [comment]
Thanks @isrjo !
