### ISSUE TITLE
php warnings when running cron scripts

### ISSUE THREAD

**Issue by s0rin** [simplesamlphp/simplesamlphp-module-metarefresh#31]
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

**Describe the bug**
php warnings when running cron scripts

**To Reproduce**
1. The following script shouls update the metadata
```
# cat ssp_metadata_cron_daily.sh
#! /bin/bash
/usr/bin/curl --silent --insecure "https://<domainname>/simplesaml-$1/module.php/cron/run/daily/secret"

```
2. When running it manually very many warnings will occur (the script doesn't fail, it updates the metadata)
```
# /usr/bin/docker exec -i docker_xxx /bin/sh /var/simplesamlphp/ssp_metadata_cron_hourly.sh xxx
...
<b>Warning</b>:  Undefined array key "entityid" in <b>/var/simplesamlphp/modules/metarefresh/src/MetaLoader.php</b> on line <b>620</b><br />
<br />
<b>Deprecated</b>:  addslashes(): Passing null to parameter simplesamlphp/simplesamlphp#1 ($string) of type string is deprecated in <b>/var/simplesamlphp/modules/metarefresh/src/MetaLoader.php</b> on line <b>622</b><br />
```

**Expected behavior**
No php warnings.

**Additional question**
How should the cron module be enabled?
According to SSP2.0 documentation should be done using `touch modules/cron/enable` [1] or in `config.php` using `'module.enable' => [ 'cron' => true, … ],` ?
[1] https://simplesamlphp.org/docs/stable/cron/cron.html#preparations

**Comment by thijskh** [comment]
Can you give the XML metadata you're trying to refresh so we can reproduce the issue?

**Comment by s0rin** [comment]
Yes, but please provide me your email, I don't want to share this data here.

**Comment by thijskh** [comment]
thijs.kinkhorst@surf.nl

**Comment by tvdijen** [comment]
I've updated to docs regarding the enable-instructions: https://github.com/simplesamlphp/simplesamlphp/commit/b07c3425910fd3570bf1ca71aa48a334ad7d19a3

**Comment by TimTrojner** [comment]
I believe I'm encountering a problem related to this issue.
Running the cron job manually I get the following notice:
```
PHP Notice:  Undefined index: entityid in /opt/simplesamlphp-ds-v2/modules/metarefresh/src/MetaLoader.php on line 620
```
You can find the metadata that I'm using here:
https://ds.aai.arnes.si/metadata/arnesaai-edugain.signed.xml

To me, it looks like some IdPs are putting the metadata in a subarray. Below is the modified line which removed the notices for me:
```
$entityID = isset($m['metadata'][0]['entityid']) ? $m['metadata'][0]['entityid'] : (
  isset($m['metadata']['entityid']) ? $m['metadata']['entityid'] : ''
);
``` 

Hope this information helps.

**Comment by s0rin** [comment]
The modified line mentioned above removed the notices for me too.

**Comment by tvdijen** [comment]
@s0rin I'm curious to know if the latest release solved any of the errors you were seeing. You think you can test using v1.1.2?

**Comment by s0rin** [comment]
The current version v1.1.1 is worse, the script fails with the error :

```
Backtrace:
2 public/_include.php:31 (SimpleSAML_exception_handler)
1 vendor/symfony/error-handler/ErrorHandler.php:607 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
0 [builtin] (N/A)
Caused by: TypeError: addslashes(): Argument #1 ($string) must be of type string, null given
Backtrace:
11 modules/metarefresh/src/MetaLoader.php:623 (addslashes)
10 modules/metarefresh/src/MetaLoader.php:623 (SimpleSAML\Module\metarefresh\MetaLoader::writeMetadataFiles)
9 modules/metarefresh/src/MetaRefresh.php:137 (SimpleSAML\Module\metarefresh\MetaRefresh::runRefresh)
8 modules/metarefresh/hooks/hook_cron.php:27 (metarefresh_hook_cron)
7 src/SimpleSAML/Module.php:564 (SimpleSAML\Module::callHooks)
6 modules/cron/src/Cron.php:55 (SimpleSAML\Module\cron\Cron::runTag)
5 modules/cron/src/Controller/Cron.php:149 (SimpleSAML\Module\cron\Controller\Cron::run)
4 vendor/symfony/http-kernel/HttpKernel.php:163 (Symfony\Component\HttpKernel\HttpKernel::handleRaw)
3 vendor/symfony/http-kernel/HttpKernel.php:75 (Symfony\Component\HttpKernel\HttpKernel::handle)
2 vendor/symfony/http-kernel/Kernel.php:202 (Symfony\Component\HttpKernel\Kernel::handle)
1 src/SimpleSAML/Module.php:234 (SimpleSAML\Module::process)
0 public/module.php:17 (N/A)
```

but it seems v1.1.2 fixes it, no more errors occurs

`RUN composer require simplesamlphp/simplesamlphp-module-metarefresh:1.1.2`
