### ISSUE TITLE
Composer dependency issues after v1.0.7 with SSP v2.0.6

### ISSUE THREAD

**Issue by rcnsheppardp** [simplesamlphp/simplesamlphp-module-metarefresh#32]
Attempting to install v1.1 or v1.2 of this module against the `composer.lock` supplied with the latest stable simplesamlphp v2.0.6 causes composer dependency errors.  It may be possible to manipulate manually, but attempting to upgrade assert from 0.8 to 1.0 still causes an error:

`$ composer require simplesamlphp/assert:^1.0 --no-install`

> ./composer.json has been updated
> Running composer update simplesamlphp/assert
> Loading composer repositories with package information
> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Root composer.json requires simplesamlphp/assert ^1.0, found simplesamlphp/assert[v1.0.0, ..., v1.0.5] but these were not loaded, likely because it conflicts with another require.
>   Problem 2
>     - simplesamlphp/composer-module-installer is locked to version v1.3.4 and an update of this package was not requested.
>     - simplesamlphp/composer-module-installer v1.3.4 requires simplesamlphp/assert ^0.8.0 || ^1.0 -> found simplesamlphp/assert[v0.8.0, v1.0.0, ..., v1.0.5] but these were not loaded, likely because it conflicts with another require.
>   Problem 3
>     - simplesamlphp/simplesamlphp-module-adfs is locked to version v2.0.2 and an update of this package was not requested.
>     - simplesamlphp/simplesamlphp-module-adfs v2.0.2 requires simplesamlphp/assert ^0.8.0 || ^1.0 -> found simplesamlphp/assert[v0.8.0, v1.0.0, ..., v1.0.5] but these were not loaded, likely because it conflicts with another require.
>   Problem 4
>     - simplesamlphp/xml-security is locked to version v0.6.6 and an update of this package was not requested.
>     - simplesamlphp/xml-security v0.6.6 requires simplesamlphp/assert ^0.8.0 -> found simplesamlphp/assert[v0.8.0] but it conflicts with your root composer.json require (^1.0).
>   Problem 5
>     - simplesamlphp/composer-module-installer v1.3.4 requires simplesamlphp/assert ^0.8.0 || ^1.0 -> found simplesamlphp/assert[v0.8.0, v1.0.0, ..., v1.0.5] but these were not loaded, likely because it conflicts with another require.
>     - simplesamlphp/simplesamlphp-assets-base v2.0.6 requires simplesamlphp/composer-module-installer ^1.3.2 -> satisfiable by simplesamlphp/composer-module-installer[v1.3.4].
>     - simplesamlphp/simplesamlphp-assets-base is locked to version v2.0.6 and an update of this package was not requested.
> 
> Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
> 
> Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by tvdijen** [comment]
Hi @rcnsheppardp !
You shouldn't be upgrading the assert-library. v1.1 of this module should be compatible with SSP 2.0.6.
I now see it's not, so I've tagged v1.1.1.. Can you try this one?

**Comment by rcnsheppardp** [comment]
Yep that's great, `composer require simplesamlphp/simplesamlphp-module-metarefresh:^1.1` happily installs on SSP 2.0.6 now - many thanks for the quick reply and resolution.
