### ISSUE TITLE
Add support for DER certificates

### ISSUE THREAD

**Issue by jaakristioja** [simplesamlphp/simplesamlphp-module-metarefresh#38]
The documentation for the `certificates` option is as follows:

https://github.com/simplesamlphp/simplesamlphp-module-metarefresh/blob/1631d53e9578e9ff4f768f631f4c9678a119b51d/docs/simplesamlphp-automated_metadata.md?plain=1#L191-L196

I opted to use DER certificates, but this did not work well, as I got the following error:

```
Error during metarefresh: Unable to extract public key
```

No extra details provided. After about half an hour of debugging and reading the source code I reached the conclusion that only PEM certifcates are supported. Is this correct?

Please add support for DER certificates or at least add a note to the documentation that the files referred to by `certificates` are required to be in PEM format. It might also help if there was and error message stating that it failed to parse the certificate as PEM.

Thanks! :-)

**Comment by tvdijen** [comment]
It feels a bit like stating the obvious TBH, because PHP's openssl extension doesn't support DER at all, so we can't support it even if we wanted..  I'll add a note to the docs

**Comment by jaakristioja** [comment]
> It feels a bit like stating the obvious TBH, because PHP's openssl extension doesn't support DER at all, so we can't support it even if we wanted.. I'll add a note to the docs

I suppose such specifics might be obvious to SimpleSAMLphp developers, but necessarily to all others.

Anyway, thank you! 😃
